import {t, tMessage, getLocale} from '../i18n.js';
import {Comparison} from './Comparison';
import {useState} from 'react';
import {Download,Play,FolderOpen,Check,AudioLines,ArrowUpRight,ShieldCheck,FileAudio,LoaderCircle,Headphones} from 'lucide-react';
import {type Project,type Format,type Variant,type RenderResult,clock,formatDate} from '../model';
import {Empty,StatusIcon} from './Primitives';
export function Exports({project,update,render,busy,play,reveal,saveFile}:{project:Project;update:(fn:(p:Project)=>Project)=>void;render:(format:Format,allVariants?:boolean)=>void;busy:string|null;play:(url:string)=>void;reveal:(path:string)=>void;saveFile:(path:string)=>void}){
 const [format,setFormat]=useState<Format>('wav');const [selected,setSelected]=useState<string|null>(null);const latest=project.exports.find(r=>r.id===selected)||project.exports.at(-1);
 return <div className="content-page export-page"><div className="page-heading"><div><span className="eyebrow">{t("OSTATNI KROK. DOPRACOWANY DŹWIĘK.")}</span><h1>{t("Gotowe do ")}<em>{t("odsłuchu.")}</em></h1><p>{t("Wyeksportuj sesję i sprawdź pomiary gotowego pliku.")}</p></div></div>
 <div className="export-layout"><section className="export-config"><div className="panel-heading"><span className="feature-icon violet"><Download size={20}/></span><div><h2>{t("Eksport sesji")}</h2><p>{project.name} · {clock(project.duration)}</p></div></div><label className="field">{t("Słyszalność głosu")}<select value={project.variant} onChange={e=>update(p=>({...p,variant:e.target.value as Variant}))}><option value="CLEAR">{t("CLEAR · wyraźny głos")}</option><option value="LOW">{t("LOW · subtelny głos")}</option><option value="MASKED">{t("MASKED · maskowany głos")}</option><option value="CONTROL">{t("CONTROL · samo tło, bez głosów i pulsu")}</option></select></label><span className="field-label">{t("Format pliku")}</span><div className="format-options">{[{id:'wav' as const,label:'WAV',desc:t("Master · bez strat")},{id:'flac' as const,label:'FLAC',desc:t("Mniejszy · bez strat")},{id:'mp3' as const,label:'MP3',desc:t("320 kb/s · do dzielenia")}].map(f=><button key={f.id} onClick={()=>setFormat(f.id)} className={format===f.id?'selected':''}><FileAudio size={20}/><strong>{f.label}</strong><span>{f.desc}</span>{format===f.id&&<Check className="format-check" size={14}/>}</button>)}</div><div className="export-spec"><div><span>{t("Próbkowanie")}</span><strong>48 kHz</strong></div><div><span>{format==='mp3'?'Bitrate':t("Głębia")}</span><strong>{format==='mp3'?'320 kb/s':'24-bit'}</strong></div><div><span>{t("Cel głośności")}</span><strong>{project.targetLufs} LUFS</strong></div><div><span>{t("Limit true peak")}</span><strong>{format==='mp3'?'−2':'−1'} dBTP</strong></div></div><button className="button primary full-width export-action" disabled={!!busy||(!project.layers.some(l=>!l.muted)&&project.background.kind==='none')} onClick={()=>render(format)}>{busy==='render'?<LoaderCircle size={18} className="spin"/>:<Download size={18}/>} {busy==='render'?t("Renderowanie sesji…"):t("Eksportuj nagranie")}</button><button className="button ghost full-width" disabled={!!busy||!project.layers.some(l=>!l.muted)} onClick={()=>render(format,true)}>{t("Eksportuj komplet · CLEAR / LOW / MASKED")}</button><p className="service-note"><ShieldCheck size={14}/>{t("Audio przetwarzane lokalnie. Pomiar po każdym eksporcie.")}</p></section>
 <section className="quality-panel"><div className="panel-heading"><span className="feature-icon blue"><ShieldCheck size={20}/></span><div><h2>{t("Kontrola jakości")}</h2><p>{latest?t("Pomiar pliku · {0} / {1}", [latest.variant, latest.format.toUpperCase()]):t("Rzetelne pomiary, czytelne wyniki")}</p></div></div>{latest?<><div className="quality-metrics"><div><span>{t("Głośność zintegrowana")}</span><strong>{latest.metrics.integratedLufs?.toFixed(1)??'—'}<small>LUFS-I</small></strong></div><div><span>{t("Szczyt rzeczywisty · est.")}</span><strong>{latest.metrics.truePeakDbtp?.toFixed(1)??'—'}<small>dBTP</small></strong></div></div><div className="quality-checks">{latest.checks.map((c,i)=><div className={`quality-check ${c.status}`} key={i}><StatusIcon status={c.status}/><div><strong>{tMessage(c.label)}</strong><p>{tMessage(c.detail)}</p></div></div>)}</div></>:<div className="quality-empty"><div className="quality-rings"><ShieldCheck size={35}/></div><h3>{t("Najpierw plik. Potem pomiar.")}</h3><p>{t("Po eksporcie pojawią się głośność, true peak, format i wyniki kontroli technicznej.")}</p><div><span>LUFS-I <b>—</b></span><span>TRUE PEAK <b>—</b></span><span>FORMAT <b>—</b></span></div></div>}</section></div>
 <section className="export-history"><div className="subheading"><div><span className="eyebrow">{t("ZAPISANE WERSJE")}</span><h2>{t("Twoje eksporty ")}<span className="count-tag">{project.exports.length}</span></h2></div></div>{project.exports.length?<div className="export-list">{[...project.exports].reverse().map(r=><div key={r.id} className={`export-row ${latest?.id===r.id?'selected':''}`}><button className="round-play" aria-label={t("Odsłuchaj {0} {1}", [r.variant, r.format])} onClick={()=>play(r.url)}><Play size={14} fill="currentColor"/></button><button className="export-name" onClick={()=>setSelected(r.id)}><strong>{project.name} <span>{r.variant}</span></strong><small>{formatDate(r.createdAt)} · {clock(r.duration)} · {r.format.toUpperCase()}</small></button><span className="export-loudness">{r.metrics.integratedLufs?.toFixed(1)??'—'} <small>LUFS</small></span><button className="icon-button" title={t("Pokaż w folderze")} aria-label={t("Pokaż w folderze")} onClick={()=>reveal(r.path)}><FolderOpen size={17}/></button><button className="button small ghost" onClick={()=>saveFile(r.path)}><Download size={15}/>{t("Zapisz jako")}</button></div>)}</div>:<Empty icon={<Headphones size={27}/>} title={t("Tutaj zostaną Twoje gotowe sesje.")}>{t("Każdy eksport zachowuje własny plik i raport. Możesz wrócić do poprzednich wersji w dowolnej chwili.")}</Empty>}</section>
 <Comparison key={project.id} project={project} update={update}/>
 </div>;
}
