import {t, tMessage, getLocale} from '../i18n.js';
import {Comparison} from './Comparison';
import {useCallback,useRef,useState} from 'react';
import {AnimatePresence} from 'motion/react';
import './Exports.css';
import {Download,Play,FolderOpen,Check,Trash2,ShieldCheck,FileAudio,LoaderCircle,Headphones} from 'lucide-react';
import {type Project,type Format,type Variant,type RenderResult,clock,formatDate} from '../model';
import {Empty,StatusIcon,Modal} from './Primitives';
export function Exports({project,update,render,busy,play,reveal,saveFile,removeExport}:{project:Project;update:(fn:(p:Project)=>Project)=>void;render:(format:Format,allVariants?:boolean)=>void;busy:string|null;play:(url:string)=>void;reveal:(path:string)=>void;saveFile:(path:string)=>void;removeExport:(result:RenderResult,trash:boolean)=>Promise<void>}){
 const [format,setFormat]=useState<Format>('wav');const [selected,setSelected]=useState<string|null>(null);const latest=project.exports.find(r=>r.id===selected)||project.exports.at(-1);
 const pl=getLocale()==='pl';
 const [deleting,setDeleting]=useState<RenderResult|null>(null);const [pending,setPending]=useState<'history'|'trash'|null>(null);const [deleteError,setDeleteError]=useState('');const deleteLock=useRef(false);
 const closeDelete=useCallback(()=>{if(!deleteLock.current){setDeleting(null);setDeleteError('');}},[]);
 const deleteSelected=async(trash:boolean)=>{if(!deleting||deleteLock.current)return;deleteLock.current=true;setPending(trash?'trash':'history');setDeleteError('');try{await removeExport(deleting,trash);setSelected(null);setDeleting(null);}catch(error){setDeleteError(error instanceof Error?tMessage(error.message):(pl?'Nie udało się usunąć eksportu. Spróbuj ponownie.':'Could not remove the export. Please try again.'));}finally{deleteLock.current=false;setPending(null);}};
 const hasSolo=project.layers.some(l=>l.solo&&!l.muted);const hasVoices=!(project.background.solo&&!project.background.muted&&project.background.kind!=='none')&&project.layers.some(l=>!l.muted&&l.offset<project.duration&&(!hasSolo||l.solo));
 const hasBackground=project.background.kind!=='none'&&!project.background.muted&&!(project.background.kind==='file'&&!project.background.path);
 const deepUnavailable=project.variant==='DEEP'&&(!hasBackground||!hasVoices);
 return <div className="content-page export-page"><div className="page-heading"><div><span className="eyebrow">{t("OSTATNI KROK. DOPRACOWANY DŹWIĘK.")}</span><h1>{t("Gotowe do ")}<em>{t("odsłuchu.")}</em></h1><p>{t("Wyeksportuj sesję i sprawdź pomiary gotowego pliku.")}</p></div></div>
 <div className="export-layout"><section className="export-config"><div className="panel-heading"><span className="feature-icon violet"><Download size={20}/></span><div><h2>{t("Eksport sesji")}</h2><p>{project.name} · {clock(project.duration)}</p></div></div><label className="field">{t("Słyszalność głosu")}<select value={project.variant} onChange={e=>update(p=>({...p,variant:e.target.value as Variant}))}><option value="CLEAR">{t("CLEAR · wyraźny głos")}</option><option value="LOW">{t("LOW · subtelny głos")}</option><option value="MASKED">{t("MASKED · maskowany głos")}</option><option value="DEEP">{pl?"DEEP · głębokie maskowanie":"DEEP · Deep Mask"}</option><option value="CONTROL">{t("CONTROL · samo tło, bez głosów i pulsu")}</option></select></label><span className="field-label">{t("Format pliku")}</span><div className="format-options">{[{id:'wav' as const,label:'WAV',desc:t("Master · bez strat")},{id:'flac' as const,label:'FLAC',desc:t("Mniejszy · bez strat")},{id:'mp3' as const,label:'MP3',desc:t("320 kb/s · do dzielenia")}].map(f=><button key={f.id} onClick={()=>setFormat(f.id)} className={format===f.id?'selected':''}><FileAudio size={20}/><strong>{f.label}</strong><span>{f.desc}</span>{format===f.id&&<Check className="format-check" size={14}/>}</button>)}</div><div className="export-spec"><div><span>{t("Próbkowanie")}</span><strong>48 kHz</strong></div><div><span>{format==='mp3'?'Bitrate':t("Głębia")}</span><strong>{format==='mp3'?'320 kb/s':'24-bit'}</strong></div><div><span>{t("Cel głośności")}</span><strong>{project.targetLufs} LUFS</strong></div><div><span>{t("Limit true peak")}</span><strong>{format==='mp3'?'−2':'−1'} dBTP</strong></div></div><button className="button primary full-width export-action" disabled={!!busy||deepUnavailable||(project.variant==='CONTROL'?!hasBackground:!hasVoices&&!hasBackground)} onClick={()=>render(format)}>{busy==='render'?<LoaderCircle size={18} className="spin"/>:<Download size={18}/>} {busy==='render'?t("Renderowanie sesji…"):t("Eksportuj nagranie")}</button><button className="button ghost full-width" disabled={!!busy||!hasVoices} onClick={()=>render(format,true)}>{pl?"Eksportuj komplet · CLEAR / LOW / MASKED / DEEP":"Export all · CLEAR / LOW / MASKED / DEEP"}</button>{deepUnavailable&&<p className="export-requirement" role="status">{pl?"DEEP wymaga aktywnego głosu i słyszalnego tła. Włącz głos i tło oraz wyłącz Solo tła.":"DEEP requires an active voice and audible background. Enable a voice and background, and turn off background Solo."}</p>}{!hasBackground&&<p className="export-requirement">{pl?"Komplet pominie DEEP, dopóki słyszalne tło nie będzie dostępne.":"The batch skips DEEP until an audible background is available."}</p>}<p className="service-note"><ShieldCheck size={14}/>{t("Audio przetwarzane lokalnie. Pomiar po każdym eksporcie.")}</p></section>
 <section className="quality-panel"><div className="panel-heading"><span className="feature-icon blue"><ShieldCheck size={20}/></span><div><h2>{t("Kontrola jakości")}</h2><p>{latest?t("Pomiar pliku · {0} / {1}", [latest.variant, latest.format.toUpperCase()]):t("Rzetelne pomiary, czytelne wyniki")}</p></div></div>{latest?<><div className="quality-metrics"><div><span>{t("Głośność zintegrowana")}</span><strong>{latest.metrics.integratedLufs?.toFixed(1)??'—'}<small>LUFS-I</small></strong></div><div><span>{t("Szczyt rzeczywisty · est.")}</span><strong>{latest.metrics.truePeakDbtp?.toFixed(1)??'—'}<small>dBTP</small></strong></div></div><div className="quality-checks">{latest.checks.map((c,i)=><div className={`quality-check ${c.status}`} key={i}><StatusIcon status={c.status}/><div><strong>{tMessage(c.label)}</strong><p>{tMessage(c.detail)}</p></div></div>)}</div></>:<div className="quality-empty"><div className="quality-rings"><ShieldCheck size={35}/></div><h3>{t("Najpierw plik. Potem pomiar.")}</h3><p>{t("Po eksporcie pojawią się głośność, true peak, format i wyniki kontroli technicznej.")}</p><div><span>LUFS-I <b>—</b></span><span>TRUE PEAK <b>—</b></span><span>FORMAT <b>—</b></span></div></div>}</section></div>
 <section className="export-history"><div className="subheading"><div><span className="eyebrow">{t("ZAPISANE WERSJE")}</span><h2>{t("Twoje eksporty ")}<span className="count-tag">{project.exports.length}</span></h2></div></div>{project.exports.length?<div className="export-list">{[...project.exports].reverse().map(r=><div key={r.id} className={`export-row ${latest?.id===r.id?'selected':''}`}><button className="round-play" aria-label={t("Odsłuchaj {0} {1}", [r.variant, r.format])} onClick={()=>play(r.url)}><Play size={14} fill="currentColor"/></button><button className="export-name" onClick={()=>setSelected(r.id)}><strong>{project.name} <span>{r.variant}</span></strong><small>{formatDate(r.createdAt)} · {clock(r.duration)} · {r.format.toUpperCase()}</small></button><span className="export-loudness">{r.metrics.integratedLufs?.toFixed(1)??'—'} <small>LUFS</small></span><button className="icon-button" title={t("Pokaż w folderze")} aria-label={t("Pokaż w folderze")} onClick={()=>reveal(r.path)}><FolderOpen size={17}/></button><button className="button small ghost" onClick={()=>saveFile(r.path)}><Download size={15}/>{t("Zapisz jako")}</button><button className="icon-button export-delete" disabled={!!pending||!!busy} title={pl?"Usuń eksport":"Remove export"} aria-label={pl?`Usuń eksport ${r.variant} ${r.format}`:`Remove export ${r.variant} ${r.format}`} onClick={()=>{setDeleteError('');setDeleting(r);}}><Trash2 size={17}/></button></div>)}</div>:<Empty icon={<Headphones size={27}/>} title={t("Tutaj zostaną Twoje gotowe sesje.")}>{t("Każdy eksport zachowuje własny plik i raport. Możesz wrócić do poprzednich wersji w dowolnej chwili.")}</Empty>}</section>
 <AnimatePresence>{deleting&&<Modal key={deleting.id} title={pl?'Usuń eksport':'Remove export'} onClose={closeDelete}><div className="export-delete-dialog" aria-busy={!!pending}><p className="modal-intro">{deleting.variant} · {deleting.format.toUpperCase()} · {formatDate(deleting.createdAt)}</p><p className="export-delete-path">{deleting.path}</p><button className="export-delete-choice" disabled={!!pending} onClick={()=>void deleteSelected(false)}><span>{pending==='history'?<LoaderCircle size={18} className="spin"/>:<FileAudio size={18}/>}<strong>{pl?'Usuń tylko z historii':'Remove from history only'}</strong></span><small>{pl?'Plik pozostanie na dysku. Zniknie wpis eksportu i jego raport.':'The file stays on disk. Removes the export entry and its report.'}</small></button><button className="export-delete-choice trash" disabled={!!pending} onClick={()=>void deleteSelected(true)}><span>{pending==='trash'?<LoaderCircle size={18} className="spin"/>:<Trash2 size={18}/>}<strong>{pl?'Przenieś plik do Kosza':'Move file to Recycle Bin'}</strong></span><small>{pl?'Przenosi rzeczywisty plik utworzony przez aplikację do Kosza Windows i usuwa wpis z historii. Kopie zapisane w innych miejscach pozostają bez zmian.':'Moves the actual app-generated file to the Windows Recycle Bin and removes its history entry. Copies saved elsewhere remain unchanged.'}</small></button>{deleteError&&<p className="export-delete-error" role="alert">{deleteError}</p>}<div className="modal-actions"><button className="button ghost" disabled={!!pending} onClick={closeDelete}>{pl?'Anuluj':'Cancel'}</button></div></div></Modal>}</AnimatePresence>
 <Comparison key={`${project.id}-${project.exports.map(r=>r.id).join()} `} project={project} update={update}/>
 </div>;
}
