import {t, tMessage, getLocale} from '../i18n.js';
import {AnimatePresence,motion} from 'motion/react';
import {AudioLines,Plus,SlidersHorizontal,Volume2,VolumeX,Headphones,MoreHorizontal,Trash2,RotateCcw,ArrowRight,CloudRain,Wind,FolderOpen,ChevronDown} from 'lucide-react';
import {useState} from 'react';
import {type Project,type Layer,type Role,roleLabels,clock,db} from '../model';
import {Range,RoleBadge,Toggle} from './Primitives';
import {useAppMotion,quickSpring} from '../MotionPreferences';
import {BackgroundControls} from './BackgroundControls';
import {Waveform} from './Waveform';
export function Studio({project,update,addAudio,importBackground,goVoices,position,selectedId,selectLayer,busy}:{project:Project;update:(fn:(p:Project)=>Project)=>void;addAudio:()=>void;importBackground:()=>void;goVoices:()=>void;position:number;selectedId:string|null;selectLayer:(s:string|null)=>void;busy:boolean}){
  const [advanced,setAdvanced]=useState(false);
  const [backgroundSelected,setBackgroundSelected]=useState(false);
  const copy=(pl:string,en:string)=>getLocale()==='pl'?pl:en;
  const {reduced}=useAppMotion();
  const selected=project.layers.find(l=>l.id===selectedId);
  const edit=(patch:Partial<Layer>)=>update(p=>({...p,layers:p.layers.map(l=>l.id===selectedId?{...l,...patch}:l)}));
  const setBackground=(kind:Project['background']['kind'])=>update(p=>({...p,background:{...p.background,kind}}));
  const backgroundSolo=project.background.kind!=='none'&&project.background.solo&&!project.background.muted;
  const anySolo=project.layers.some(s=>s.solo&&!s.muted)||(project.background.kind!=='none'&&project.background.solo&&!project.background.muted);
  const active=backgroundSolo?0:project.layers.filter(l=>!l.muted&&l.offset<project.duration&&(!anySolo||l.solo)).length;
  const fullTakeDuration=Math.max(project.duration,...project.layers.filter(l=>!l.muted&&l.offset<project.duration&&(!anySolo||l.solo)).map(l=>l.offset+l.duration/l.speed));
  return <div className="studio-layout">
    <section className="studio-main"><div className="section-heading"><div><h1>{project.name}</h1><p>{t("Ułóż głosy, dobierz muzykę i odsłuchaj swój miks.")}</p></div></div>
      <div className="session-toolbar"><div className="segmented variants" aria-label={t("Słyszalność głosu")}>{(['CLEAR','LOW','MASKED','DEEP'] as const).map(v=><button key={v} className={project.variant===v?'active':''} onClick={()=>update(p=>({...p,variant:v}))}>{project.variant===v&&<motion.span className="variant-lens" layoutId="variant-lens" transition={reduced?{duration:0}:quickSpring}/>}<span className="variant-text">{v==='CLEAR'?t("Wyraźny"):v==='LOW'?t("Subtelny"):v==='MASKED'?t("Maskowany"):'Deep Mask'}</span></button>)}</div><span className="micro-label">{project.variant==='CLEAR'?t("Głos na pierwszym planie"):project.variant==='LOW'?t("Głos pod delikatnym tłem"):project.variant==='MASKED'?t("Głęboko pod warstwą tła"):project.variant==='DEEP'?copy("Głosy dopasowane do cichego tła","Voices balanced beneath a quiet background"):t("Tylko tło · wersja kontrolna")}</span><button className="button small ghost" onClick={addAudio} disabled={busy}><Plus size={15}/>{t("Dodaj audio")}</button></div>
      {project.variant==='DEEP'&&<p className="deep-mask-note" role="status">{project.background.kind==='none'||project.background.muted?copy("Deep Mask wymaga aktywnego tła. Wybierz szum lub muzykę i wyłącz wyciszenie.","Deep Mask needs an active background. Choose noise or music and unmute it."):project.background.solo?copy("Solo odtwarza samo tło. Wyłącz je, aby odsłuchać miks Deep Mask.","Solo previews the background alone. Turn it off to hear the Deep Mask mix."):copy("Deep Mask dopasowuje poziom głosów do tła. Odsłuchaj cichy fragment przed eksportem.","Deep Mask adjusts voice levels to the background. Listen to a quiet passage before exporting.")}</p>}
      <div className="timeline"><div className="timeline-top"><span><AudioLines size={15}/>{t("Ścieżki sesji ")}<b>{project.layers.length+Number(project.background.kind!=='none')}</b></span><span>48 000 Hz <span className="tiny-dot"/> STEREO</span></div>
        <div className="ruler"><span className="ruler-label">{t("WARSTWA")}</span><div>{Array.from({length:7},(_,i)=><span key={i}>{clock(project.duration*i/6)}</span>)}</div></div>
        <div className="lanes"><AnimatePresence initial={false}>
        {project.layers.length?project.layers.map((l,i)=><motion.div layout="position" initial={{opacity:0,y:reduced?0:8}} animate={{opacity:1,y:0}} exit={{opacity:0,x:reduced?0:-12,transition:{duration:.13}}} transition={reduced?{duration:.1}:quickSpring} className={`track role-${l.role} ${l.muted||backgroundSolo||(anySolo&&!l.solo)?'muted':''} ${selectedId===l.id?'selected':''}`} key={l.id} onClick={()=>{setBackgroundSelected(false);selectLayer(l.id);}}>
          <div className="track-info"><div><RoleBadge role={l.role}/><span className="track-title">{l.name.replace(/\.[^.]+$/,'')}<small>{roleLabels[l.role]} · {l.speed}× {l.reverse?'· reverse':''}</small></span></div><div className="track-tools"><button className={`tiny-button ${l.muted?'pressed':''}`} title={t("Wycisz")} aria-label={t("Wycisz {0}", [l.name])} onClick={e=>{e.stopPropagation();update(p=>({...p,layers:p.layers.map(x=>x.id===l.id?{...x,muted:!x.muted}:x)}));}}>{l.muted?<VolumeX size={14}/>:<Volume2 size={14}/>}</button><button className={`tiny-button ${l.solo?'pressed':''}`} aria-label={`Solo ${l.name}`} onClick={e=>{e.stopPropagation();update(p=>({...p,layers:p.layers.map(x=>x.id===l.id?{...x,solo:!x.solo}:x)}));}}>S</button><span>{db(l.gainDb)}</span><button className="tiny-button track-more" aria-label={t("Ustawienia {0}", [l.name])}><MoreHorizontal size={15}/></button></div></div>
          <div className="track-audio"><div className="audio-clip" style={{marginLeft:`${l.offset/project.duration*100}%`,width:`${Math.max(0,100-l.offset/project.duration*100)}%`}}><div className="clip-caption"><span>{l.reverse?'↶ ':''}{l.name}</span><span>↻ LOOP</span></div><Waveform peaks={l.peaks} color={l.role==='A'?'--role-a':l.role==='B'?'--role-b':'--role-c'} height={52}/></div></div>
        </motion.div>):(['A','B','C'] as Role[]).map(role=><div className={`track empty-track role-${role}`} key={role}><div className="track-info"><div><RoleBadge role={role}/><span className="track-title">{roleLabels[role]}<small>{role==='A'?t("Twój punkt wyjścia"):role==='B'?t("Kierunek i działanie"):t("Przestrzeń dla wyobraźni")}</small></span></div></div><button className="empty-lane" onClick={goVoices}><Plus size={16}/><span>{t("Dodaj głos do warstwy ")}{role}</span></button></div>)}
        </AnimatePresence>{project.background.kind!=='none'&&<div className={`track background-track ${project.background.muted?'muted':''} ${backgroundSelected&&!selected?'selected':''}`} role="button" tabIndex={0} aria-label={copy("Ustawienia tła","Background settings")} onClick={()=>{selectLayer(null);setBackgroundSelected(true);}} onKeyDown={e=>{if(e.target===e.currentTarget&&(e.key==='Enter'||e.key===' ')){e.preventDefault();selectLayer(null);setBackgroundSelected(true);}}}><div className="track-info"><div><span className="background-icon"><Wind size={17}/></span><span className="track-title">{project.background.kind==='brown'?'Brown noise':project.background.kind==='pink'?'Pink noise':project.background.name||t("Własne tło")}<small>{t("Atmosfera · pełna długość")}</small></span></div><div className="track-tools"><button className={`tiny-button ${project.background.muted?'pressed':''}`} aria-label={copy("Wycisz tło","Mute background")} aria-pressed={!!project.background.muted} onClick={e=>{e.stopPropagation();update(p=>({...p,background:{...p.background,muted:!p.background.muted}}));}}>{project.background.muted?<VolumeX size={14}/>:<Volume2 size={14}/>}</button><button className={`tiny-button ${project.background.solo?'pressed':''}`} aria-label={copy("Solo tła","Solo background")} aria-pressed={!!project.background.solo} onClick={e=>{e.stopPropagation();update(p=>({...p,background:{...p.background,solo:!p.background.solo}}));}}>S</button><span>{db(project.background.gainDb)}</span><span className="auto-badge">{t("TŁO")}</span></div></div><div className="track-audio"><div className="noise-clip"><div className="noise-texture"/><div className="noise-caption"><Wind size={14}/>{project.background.kind==='file'?t("Importowane nagranie"):t("Generowane podczas renderu")}<span>{t("↻ CIĄGŁE")}</span></div></div></div></div>}
        <div className="playhead-container"><div className="playhead" style={{transform:`translateX(${Math.min(position/project.duration,1)*100}%)`}}><i/></div></div>
        </div><div className="timeline-footer"><span>{active} {active===1?t("aktywna warstwa głosu"):t("aktywnych warstw głosu")}</span><span><span className="tiny-dot lavender"/>{t("Automatyczne przejścia na początku i końcu")}</span></div>
      </div>
      {!project.layers.length&&<div className="next-step"><div className="step-orbit"><AudioLines size={23}/></div><div><strong>{t("Twój tekst jest gotowy. Teraz nadaj mu głos.")}</strong><p>{t("Wygeneruj nagranie, użyj mikrofonu lub dodaj własne pliki.")}</p></div><button className="button ghost" onClick={goVoices}>{t("Przejdź do głosów ")}<ArrowRight size={16}/></button></div>}
      <div className="atmosphere"><div className="subheading"><div><span className="eyebrow">{t("DRUGI PLAN, PIERWSZE WRAŻENIE")}</span><h2>{t("Zbuduj atmosferę")}</h2></div><button className="button ghost" disabled={busy} onClick={importBackground}><Plus size={15}/>{t("Dodaj muzykę")}</button></div>{project.background.kind==='file'&&<div className="music-source"><AudioLines size={22}/><div><strong>{project.background.name}</strong><small>{t("Muzyka w tle · zapętlenie do długości sesji")}</small></div><button className="button small ghost" disabled={busy} onClick={importBackground}>{t("Zmień plik")}</button><button className="icon-button" aria-label={t("Usuń muzykę z tła")} onClick={()=>setBackground('none')}><Trash2 size={16}/></button></div>}<div className="atmosphere-options">{[{kind:'brown' as const,name:'Brown noise',desc:t("Głębokie, miękkie otulenie"),icon:<Wind size={22}/>,style:'brown'},{kind:'pink' as const,name:'Pink noise',desc:t("Równe, subtelne wyciszenie"),icon:<CloudRain size={22}/>,style:'pink'},{kind:'none' as const,name:t("Sam głos"),desc:t("Czysta przestrzeń dla słów"),icon:<AudioLines size={22}/>,style:'clean'}].map(x=><motion.button whileHover={reduced?undefined:{y:-2}} whileTap={reduced?undefined:{scale:.985}} transition={quickSpring} key={x.kind} className={`atmosphere-option ${x.style} ${project.background.kind===x.kind?'chosen':''}`} onClick={()=>setBackground(x.kind)}><span className="atmosphere-art">{x.icon}<i/><i/><i/></span><span><strong>{x.name}</strong><small>{x.desc}</small></span><span className="radio-dot"/></motion.button>)}</div></div>
      <div className="audit-note"><Headphones size={16}/><span>{t("Najlepszy miks zaczyna się od odsłuchu. Porównaj warianty przy tej samej głośności.")}</span><span>{t("NA PODSTAWIE TWOJEGO AUDYTU")}</span></div>
    </section>
    <aside className="inspector"><header><SlidersHorizontal size={17}/><h2>{selected?t("Ustawienia warstwy"):backgroundSelected?copy("Ustawienia tła","Background settings"):t("Ustawienia sesji")}</h2>{(selected||backgroundSelected)&&<button className="button small ghost inspector-back" title={t("Wróć do sesji")} onClick={()=>{selectLayer(null);setBackgroundSelected(false);}}><RotateCcw size={14}/>{copy('Sesja','Session')}</button>}</header>
    <motion.div key={selected?.id??(backgroundSelected?'background':'session')} initial={{opacity:0,x:reduced?0:8}} animate={{opacity:1,x:0}} transition={reduced?{duration:.1}:quickSpring}>{selected?<><div className="inspector-block"><div className="selected-layer"><RoleBadge role={selected.role}/><strong>{selected.name}</strong></div><label className="field">{t("Nazwa ścieżki")}<input value={selected.name} maxLength={300} onChange={e=>edit({name:e.target.value})}/></label><label className="field">{t("Rola warstwy")}<select value={selected.role} onChange={e=>edit({role:e.target.value as Role})}>{(['A','B','C'] as Role[]).map(r=><option key={r} value={r}>{r} · {roleLabels[r]}</option>)}</select></label><Range label={t("Poziom głosu")} value={selected.gainDb} min={-60} max={12} format={db} onChange={gainDb=>edit({gainDb})}/><Range label={t("Panorama")} value={selected.pan} min={-1} max={1} step={0.01} format={n=>n===0?t("Środek"):`${n<0?'L':'R'} ${Math.round(Math.abs(n)*100)}%`} onChange={pan=>edit({pan})}/></div><div className="inspector-block"><h3>{t("Przetwarzanie")}</h3><Range label={t("Tempo · zachowaj ton")} value={selected.speed} min={0.5} max={2} step={0.05} format={n=>`${n.toFixed(2)}×`} onChange={speed=>edit({speed})}/><Range label={t("Początek warstwy")} value={selected.offset} min={0} max={Math.max(0,project.duration-1)} format={clock} onChange={offset=>edit({offset})}/><div className="toggle-row"><div>{t("Odtwarzaj od tyłu")}<small>{t("Reverse całego nagrania")}</small></div><Toggle checked={selected.reverse} onChange={reverse=>edit({reverse})} label={t("Odtwarzaj od tyłu")}/></div><p className="inspector-hint">{t("Nagranie powtarza się do końca sesji. Zmiana tempa zachowuje pełną treść i wysokość głosu.")}</p></div><button className="button danger subtle" onClick={()=>{update(p=>({...p,layers:p.layers.filter(l=>l.id!==selected.id)}));selectLayer(null);}}><Trash2 size={15}/>{t("Usuń warstwę")}</button></>:backgroundSelected?<BackgroundControls project={project} update={update}/>:<>
      <div className="inspector-block"><label className="field">{t("Długość sesji")}<div className="input-with-unit"><input aria-label={t("Długość sesji w sekundach")} type="number" min={5} max={3600} value={project.duration} onChange={e=>{const n=Number(e.target.value);if(n>=5&&n<=3600)update(p=>({...p,duration:n,layers:p.layers.map(l=>({...l,offset:Math.min(l.offset,n-1)}))}));}}/><span>{t("sekund")}</span></div></label><div className="duration-shortcuts">{[60,180,300,600].map(n=><button key={n} className={project.duration===n?'active':''} onClick={()=>update(p=>({...p,duration:n,layers:p.layers.map(l=>({...l,offset:Math.min(l.offset,n-1)}))}))}>{n/60} min</button>)}</div>{fullTakeDuration>project.duration+.05&&<p className="inspector-hint" role="status">{copy(`Eksport wydłuży się do ${clock(fullTakeDuration)}, żeby nie uciąć aktywnego nagrania.`,`Export extends to ${clock(fullTakeDuration)} so the active recording is not cut off.`)}</p>}</div>
      <BackgroundControls project={project} update={update}/>
      <div className="inspector-block"><div className="toggle-row"><div>{t("Puls izochroniczny")}<small>{t("Subtelna modulacja tła")}</small></div><Toggle label={t("Puls izochroniczny")} checked={project.pulse.enabled} onChange={enabled=>update(p=>({...p,pulse:{...p.pulse,enabled}}))}/></div>{project.pulse.enabled&&<motion.div initial={{opacity:0,y:reduced?0:6}} animate={{opacity:1,y:0}} transition={reduced?{duration:.1}:quickSpring}><Range label={t("Częstotliwość pulsu")} value={project.pulse.hz} min={1} max={30} format={n=>`${n} Hz`} onChange={hz=>update(p=>({...p,pulse:{...p.pulse,hz}}))}/><Range label={t("Głębokość")} value={project.pulse.depth} min={0} max={0.5} step={0.01} format={n=>`${Math.round(n*100)}%`} onChange={depth=>update(p=>({...p,pulse:{...p.pulse,depth}}))}/></motion.div>}</div>
      <div className="inspector-block"><button className="disclosure" onClick={()=>setAdvanced(!advanced)}>Mastering<ChevronDown size={14} style={{transform:advanced?'rotate(180deg)':undefined}}/></button><div className="master-spec"><span>{t("Format sesji")}</span><strong>48 kHz / 24-bit</strong><span>{t("Cel głośności")}</span><strong>{project.targetLufs} LUFS</strong><span>{t("Limit true peak")}</span><strong>−1 dBTP</strong></div>{advanced&&<motion.div initial={{opacity:0,y:reduced?0:6}} animate={{opacity:1,y:0}} transition={reduced?{duration:.1}:quickSpring}><Range label={t("Docelowa głośność")} value={project.targetLufs} min={-36} max={-14} format={n=>`${n} LUFS`} onChange={targetLufs=>update(p=>({...p,targetLufs}))}/><div className="mastering-presets">{[{value:-24,label:copy("Cicho","Quiet")},{value:-18,label:copy("Standardowo","Standard")}].map(preset=><button key={preset.value} className="button small ghost" aria-pressed={project.targetLufs===preset.value} onClick={()=>update(p=>({...p,targetLufs:preset.value}))}>{preset.label} · {preset.value} LUFS</button>)}</div></motion.div>}<p className="inspector-hint">{t("Po eksporcie sprawdzimy gotowy plik. Pomiar jakości pojawi się w wynikach.")}</p></div>
      <div className="inspector-tip"><span className="mini-spark">✧</span><strong>{t("Mniej warstw. Więcej kontroli.")}</strong><p>{t("Zacznij od jednego czystego głosu i spokojnego tła. Kolejne warstwy dodawaj z intencją.")}</p></div>
    </>}</motion.div>
    </aside>
  </div>;
}
