import {useState,useRef} from 'react';
import {AnimatePresence,motion} from 'motion/react';
import {ArrowUpRight,Heart,X} from 'lucide-react';
import {getLocale} from '../i18n';
import './support.css';

export function Support({open}:{open:(url:string)=>Promise<void>}){
 const pl=getLocale()==='pl';const [expanded,setExpanded]=useState(false);const [error,setError]=useState('');const paypal=useRef<HTMLButtonElement>(null);
 async function visit(url:string){try{setError('');await open(url);}catch{setError(pl?'Nie udało się otworzyć przeglądarki.':'Could not open your browser.');}}
 const base='https://www.paypal.com/paypalme/piotrkolodz';
 return <section className="settings-section support-section"><div className="support-heading"><Heart size={17}/><div><h3>{pl?'Wesprzyj twórcę':'Support the creator'}</h3><p>{pl?'Jeśli lubisz tu tworzyć. Każda funkcja pozostaje dostępna dla wszystkich.':'If you enjoy creating here. Every feature stays available to everyone.'}</p></div></div><div className="support-links"><button className="button" onClick={()=>void visit('https://ko-fi.com/piotrkolodz')}><svg width="24" height="20" viewBox="0 0 24 20" aria-hidden="true"><path d="M3 3h14v9a5 5 0 0 1-5 5H8a5 5 0 0 1-5-5Z" fill="currentColor"/><path d="M17 4h2a3 3 0 0 1 0 6h-2" fill="none" stroke="currentColor" strokeWidth="2"/><path d="M7 7c0-2 3-2 3 0 0-2 3-2 3 0 0 2-3 4-3 4S7 9 7 7" fill="#f07272"/></svg>Ko-fi<ArrowUpRight size={14}/></button><button ref={paypal} className="button" aria-expanded={expanded} aria-controls="paypal-amounts" onClick={()=>setExpanded(v=>!v)}><span className="paypal-logo" aria-hidden="true">P</span>PayPal<ArrowUpRight size={14}/></button></div><AnimatePresence initial={false}>{expanded&&<motion.div id="paypal-amounts" className="support-amounts" initial={{opacity:0,y:-6,scale:.98}} animate={{opacity:1,y:0,scale:1}} exit={{opacity:0,y:-4}} transition={{duration:.18}}><div><strong>{pl?'Wybierz kwotę':'Choose an amount'}</strong><button className="icon-button" aria-label={pl?'Zamknij wybór kwoty':'Close amount selection'} onClick={()=>{setExpanded(false);paypal.current?.focus();}}><X size={15}/></button></div><div className="amount-options">{(pl?[10,25,50]:[3,8,15]).map(amount=><button className="button" key={amount} onClick={()=>void visit(`${base}/${amount}${pl?'PLN':'USD'}`)}>{pl?`${amount} zł`:`$${amount}`}</button>)}<button className="button ghost" onClick={()=>void visit(base)}>{pl?'Własna kwota':'Custom amount'}</button></div><small>{pl?'Otwiera PayPal w przeglądarce. Płatność zatwierdzasz tam samodzielnie.':'Opens PayPal in your browser. You confirm the payment there.'}</small></motion.div>}</AnimatePresence>{error&&<p role="alert">{error}</p>}</section>;
}
