import {useEffect,useState} from 'react';
 import {Download,RefreshCw,History,ExternalLink} from 'lucide-react';
import {getLocale} from '../i18n';
import type {UpdateStatus} from '../model';
import {Toggle} from './Primitives';
import './updates.css';

const notes=[
 {"version":"2.2.1","en":["Exports retain the end of an active vocal take instead of cutting it at the session length.","Previews clean up earlier preview files; deleting an export permanently removes its app-owned audio and report.","Importing a TXT or Markdown file replaces the untouched starter text, with a direct GitHub download page for updates."],"pl":["Eksport zachowuje koniec aktywnego nagrania zamiast ucinać go na długości sesji.","Preview sprząta wcześniejsze pliki podglądu; usunięcie eksportu trwale kasuje należące do aplikacji audio i raport.","Import TXT lub Markdown zastępuje nietknięty tekst startowy, a aktualizacje mają bezpośrednią stronę pobierania z GitHub."]},
 {"version":"2.2.0","en":["Deep Mask follows quiet passages in the background by attenuating voices.","Background controls: mute, solo, filters, pan, fades and file speed/reverse.","Quieter new sessions and finer playback volume control.","Remove exports from history or move their files to the Recycle Bin."],"pl":["Deep Mask ścisza głosy w cichych fragmentach tła.","Ustawienia tła: wyciszenie, solo, filtry, panorama, przejścia oraz tempo i reverse pliku.","Cichsze nowe sesje i dokładniejsza regulacja głośności odsłuchu.","Usuwanie eksportów z historii lub przenoszenie ich plików do Kosza."]},
 {version:'2.1.1',en:['Read a selected affirmation while recording; each take uses its text and role.','Remove recordings from the library while preserving project audio.','Release notes and GitHub update controls in Settings.'],pl:['Nagrywanie z widoczną afirmacją; nazwa i rola nagrania pochodzą ze skryptu.','Usuwanie nagrań z biblioteki z zachowaniem audio w projektach.','Historia zmian i obsługa aktualizacji GitHub w ustawieniach.']},
 {version:'2.1.0',en:['Microphone selection and flexible TXT / Markdown import.','Full animations independent of Windows preferences.','Optional Ko-fi and PayPal support.'],pl:['Wybór mikrofonu i elastyczny import TXT / Markdown.','Pełne animacje niezależne od ustawień Windows.','Opcjonalne wsparcie przez Ko-fi i PayPal.']},
 {version:'2.0.0',en:['New Windows studio with local projects, layered audio and measured exports.'],pl:['Nowe studio Windows: lokalne projekty, warstwy audio i pomiary eksportów.']}
];
export function Updates({install}:{install:()=>Promise<void>}){
 const pl=getLocale()==='pl';const api=window.auralith;
 const [status,setStatus]=useState<UpdateStatus>({phase:'unsupported',enabled:false,version:'',progress:0});const [error,setError]=useState(false);const [working,setWorking]=useState(false);
 useEffect(()=>{let live=true;const off=api?.onUpdateStatus?.(s=>{if(live)setStatus(s);});api?.updateStatus?.().then(s=>{if(live)setStatus(s);}).catch(()=>{if(live)setError(true);});return()=>{live=false;off?.();};},[]);
 async function run(action:()=>Promise<unknown>|undefined){setError(false);setWorking(true);try{await action();}catch{setError(true);}finally{setWorking(false);}}
 const labels:Record<string,string>=pl?{unconfigured:'Źródło aktualizacji nie zostało skonfigurowane.',unsupported:'Automatyczna instalacja jest dostępna w wersji z instalatora. Portable aktualizujesz ręcznie.',idle:'Sprawdzaj nowe wydania na GitHubie.',checking:'Sprawdzanie wydań…',current:'Masz najnowszą dostępną wersję.',available:`Dostępna wersja ${status.version}`,downloading:`Pobieranie · ${Math.round(status.progress)}%`,downloaded:`Wersja ${status.version} gotowa do instalacji.`,error:'Nie udało się sprawdzić lub pobrać wydania. Repozytorium musi być publiczne i zawierać pliki aktualizacji. Spróbuj ponownie.'}:{unconfigured:'No update source has been configured.',unsupported:'Automatic installation is available in the installed app. Update Portable manually.',idle:'Check GitHub for new releases.',checking:'Checking releases…',current:'You have the latest available version.',available:`Version ${status.version} is available`,downloading:`Downloading · ${Math.round(status.progress)}%`,downloaded:`Version ${status.version} is ready to install.`,error:'Could not check or download the release. The repository must be public and contain update files. Please retry.'};
 const supported=!['unconfigured','unsupported'].includes(status.phase);
 return <section className="settings-section updates-section"><span className="eyebrow">{pl?'WERSJE I AKTUALIZACJE':'RELEASES & UPDATES'}</span><h3>{pl?'Twoja wersja, na bieżąco':'Keep your studio up to date'}</h3><p role="status">{labels[status.phase]}</p>{supported&&<><div className="update-preference"><span>{pl?'Sprawdzaj automatycznie przy uruchomieniu':'Automatically check on startup'}</span><Toggle label={pl?'Automatyczne sprawdzanie aktualizacji':'Automatic update checks'} checked={status.enabled} onChange={value=>void run(()=>api?.setUpdateChecks?.(value))}/></div><p>{pl?'Gdy pojawi się wersja, pobierz właściwy instalator bezpośrednio z jej strony na GitHubie.':'When a version is available, download the correct installer directly from its GitHub release page.'}</p><div className="update-actions">{['idle','current','error'].includes(status.phase)&&<button className="button" disabled={working} onClick={()=>void run(()=>api?.checkUpdates?.())}><RefreshCw size={15}/>{pl?'Sprawdź aktualizacje':'Check for updates'}</button>}<button className="button" disabled={working} onClick={()=>void run(()=>api?.openReleasePage?.())}><ExternalLink size={15}/>{pl?'Otwórz pobieranie z GitHub':'Open GitHub downloads'}</button>{status.phase==='downloaded'&&<button className="button" disabled={working} onClick={()=>void run(install)}>{pl?'Zapisz i zainstaluj ponownie uruchamiając':'Save, install and restart'}</button>}</div></>}{error&&<p role="alert">{pl?'Nie udało się wykonać operacji. Zakończ nagrywanie lub przetwarzanie i spróbuj ponownie.':'Could not complete the action. Finish recording or processing, then try again.'}</p>}<details className="release-notes"><summary><History size={16}/>{pl?'Historia zmian':'Release notes'}</summary>{notes.map(note=><article key={note.version}><strong>{note.version}</strong><ul>{(pl?note.pl:note.en).map(line=><li key={line}>{line}</li>)}</ul></article>)}</details></section>;
}
