import {playbackGain} from './audio/playback';
import {Updates} from './components/Updates';
import {Support} from './components/Support';
import {MotionSettings,useAppMotion} from './MotionPreferences';
import {useLocale} from './useLocale';
import {t, tMessage, getLocale, setLocale} from './i18n.js';
import {useCallback,useEffect,useRef,useState} from 'react';
import {motion,AnimatePresence} from 'motion/react';
import {MaterialSwitch} from './components/MaterialSwitch';
import {GlassScene} from './components/GlassScene';
import {AudioLines,FolderOpen,FileText,Mic,SlidersHorizontal,Download,Plus,Settings,ChevronDown,ArrowUpRight,Play,Pause,SkipBack,Square,Volume2,Check,LoaderCircle,X,Minus,Maximize2,Undo2,Redo2,Search,Sparkles,WandSparkles,ArrowRight,Upload,HardDrive,Headphones,AlertCircle,Command} from 'lucide-react';
import {createProject,applyMode,duplicateProject,layerFromAsset,migrateProject,validateProject,parseScript,shouldReplaceTemplateScript,uid,modeLabels,roleLabels,clock,formatDate,type Project,type Screen,type Mode,type Role,type Line,type Asset,type Format,type RenderResult,type Progress,type Bridge} from './model';
import {Brand,Modal,RoleBadge,Range} from './components/Primitives';
import {Studio} from './components/Studio';
import {ScriptLab} from './components/ScriptLab';
import {Voices} from './components/Voices';
import {Exports} from './components/Exports';

const nav=[{id:'projects' as Screen,label:'Projekty',icon:FolderOpen},{id:'script' as Screen,label:'Tekst intencji',icon:FileText},{id:'voices' as Screen,label:'Głosy i nagrania',icon:Mic},{id:'studio' as Screen,label:'Studio',icon:SlidersHorizontal},{id:'exports' as Screen,label:'Eksporty',icon:Download}];
const unavailable=async():Promise<never>=>{throw new Error(t("Ta funkcja działa w aplikacji Windows. Otwórz Auralith Studio.exe."));};
const browserBridge:Bridge={
 bootstrap:async()=>({projects:JSON.parse(localStorage.getItem('auralith-preview')||'[]'),assets:[],version:t("2.2.1 · podgląd"),dataPath:t("Podgląd w przeglądarce")}),
 saveProject:async p=>{const projects:Project[]=JSON.parse(localStorage.getItem('auralith-preview')||'[]');const i=projects.findIndex(x=>x.id===p.id);if(i>=0)projects[i]=p;else projects.push(p);localStorage.setItem('auralith-preview',JSON.stringify(projects));return p;},
 removeExport:unavailable,removeAsset:unavailable,importAudio:unavailable,importText:unavailable,importProject:unavailable,exportProject:unavailable,synthesize:unavailable,saveRecording:unavailable,render:unavailable,cancelRender:async()=>{},onProgress:()=>()=>{},reveal:unavailable,exportFile:unavailable,windowControl:()=>{}
};
const api=window.auralith||browserBridge;

export default function App(){
 const locale=useLocale();
 const {reduced}=useAppMotion();
 useEffect(()=>{document.documentElement.lang=locale;void api.setLanguage?.(locale).catch(()=>{});},[locale]);
 const [project,setProject]=useState<Project>(()=>createProject(t("Spokojna pewność"),'spell'));const [projects,setProjects]=useState<Project[]>([]);const [assets,setAssets]=useState<Asset[]>([]);const [ready,setReady]=useState(false);const [screen,setScreen]=useState<Screen>('studio');const [busy,setBusy]=useState<string|null>(null);const [saveStatus,setSaveStatus]=useState<'saved'|'saving'|'error'>('saved');const [progress,setProgress]=useState<Progress|null>(null);const [toast,setToast]=useState<{message:string;error:boolean}|null>(null);const [modal,setModal]=useState<'new'|'settings'|null>(null);const [newName,setNewName]=useState('');const [newMode,setNewMode]=useState<Mode>('classic');const [selectedLayer,setSelectedLayer]=useState<string|null>(null);const [search,setSearch]=useState('');const [playing,setPlaying]=useState(false);const [position,setPosition]=useState(0);const [playDuration,setPlayDuration]=useState(0);const [playbackName,setPlaybackName]=useState(t("Odsłuch sesji"));const [volume,setVolume]=useState(.2);const [appInfo,setAppInfo]=useState({version:'2.2.1',dataPath:''});const [theme,setTheme]=useState(()=>localStorage.getItem('auralith-theme')==='focus'?'focus':'liquid');
 const audio=useRef<HTMLAudioElement>(null);const current=useRef(project);current.current=project;const library=useRef(projects);library.current=projects;const recordingActive=useRef(false);const history=useRef<Project[]>([]);const future=useRef<Project[]>([]);const savedSequence=useRef(0);const toastTimer=useRef<ReturnType<typeof setTimeout>|null>(null);const previewTicket=useRef(0);const previewKey=useRef('');const previewLoadingKey=useRef('');
 const notify=useCallback((message:string,error=false)=>{setToast({message,error});if(toastTimer.current)clearTimeout(toastTimer.current);toastTimer.current=setTimeout(()=>setToast(null),error?8000:4000);},[]);
 const closeModal=useCallback(()=>setModal(null),[]);
 useEffect(()=>{document.documentElement.dataset.theme=theme;localStorage.setItem('auralith-theme',theme);},[theme]);
 useEffect(()=>{let live=true;api.bootstrap().then(data=>{if(!live)return;const list=data.projects.map(migrateProject);setProjects(list);if(list[0])setProject(list[0]);setAssets(data.assets);setAppInfo({version:data.version,dataPath:data.dataPath});setReady(true);}).catch(e=>{notify(t("Nie udało się odczytać biblioteki: {0}", [e.message]),true);setReady(true);});return()=>{live=false;};},[notify]);
 useEffect(()=>{const handler=(event:Event)=>{document.querySelectorAll('audio').forEach(el=>{if(el!==event.target)el.pause();});};document.addEventListener('play',handler,true);return()=>document.removeEventListener('play',handler,true);},[]);
 useEffect(()=>api.onProgress(event=>setProgress(event)),[]);
 useEffect(()=>{if(!ready||busy==='remove-export')return;const seq=++savedSequence.current;setSaveStatus('saving');const timer=setTimeout(()=>{let p:Project;try{p=validateProject(project);}catch(e){setSaveStatus('error');return;}api.saveProject(p).then(()=>{if(seq===savedSequence.current)setSaveStatus('saved');}).catch(e=>{if(seq===savedSequence.current)setSaveStatus('error');notify(t("Zapis nie powiódł się: {0}", [e.message]),true);});},500);return()=>clearTimeout(timer);},[project,ready,notify,busy]);
 useEffect(()=>{if(audio.current)audio.current.volume=playbackGain(volume);},[volume]);
 useEffect(()=>window.auralith?.onCloseRequested?.(()=>{if(busy==='remove-export'){notify(getLocale()==='pl'?'Poczekaj na zakończenie usuwania.':'Wait for export removal to finish.',true);return;}if(recordingActive.current){notify(t("Zakończ nagrywanie przed zamknięciem aplikacji."),true);return;}api.saveProject(current.current).then(()=>api.windowControl('close-saved')).catch(e=>notify(t("Nie zamykam aplikacji: zapis projektu nie powiódł się. {0}", [e.message]),true));}),[notify,busy]);
 const setCurrent=useCallback((next:Project)=>{current.current=next;setProject(next);library.current=[next,...library.current.filter(x=>x.id!==next.id)];setProjects(library.current);},[]);
 const update=useCallback((fn:(p:Project)=>Project)=>{const p=current.current;history.current=[...history.current.slice(-39),structuredClone(p)];future.current=[];setCurrent({...fn(p),updatedAt:new Date().toISOString()});},[setCurrent]);
 const stop=useCallback(()=>{previewTicket.current++;if(previewLoadingKey.current){previewLoadingKey.current='';void api.cancelRender();}audio.current?.pause();if(audio.current)audio.current.currentTime=0;setPlaying(false);setPosition(0);},[]);
 function undo(){const previous=history.current.pop();if(previous){future.current.push(current.current);setCurrent(previous);}}
 function redo(){const next=future.current.pop();if(next){history.current.push(current.current);setCurrent(next);}}
 async function playUrl(url:string,name=t("Odsłuch nagrania")){if(!audio.current)return;audio.current.pause();audio.current.src=url;previewKey.current='';setPlaybackName(name);try{await audio.current.play();}catch{notify(t("Nie można odtworzyć pliku. Nagranie może być niedostępne."),true);}}
 async function preview(){
  if(playing){audio.current?.pause();return;}if(busy)return;
  const p=current.current;const key=JSON.stringify({...p,exports:[],updatedAt:'',name:''});
  if(previewKey.current===key&&audio.current?.src){try{await audio.current.play();}catch(e){notify(t("Nie można rozpocząć odsłuchu."),true);}return;}
  const ticket=++previewTicket.current;setBusy('preview');setProgress({stage:t("Przygotowanie odsłuchu"),progress:0});previewLoadingKey.current=key;
  try{const result=await api.render({project:p,format:'wav',preview:true});if(ticket!==previewTicket.current||key!==JSON.stringify({...current.current,exports:[],updatedAt:'',name:''}))return;previewKey.current=key;if(audio.current){audio.current.src=result.url;setPlaybackName(t("Podgląd · {0}", [clock(result.duration)]));await audio.current.play();}}
  catch(e){const message=(e as Error).message;if(!/anul|abort/i.test(message))notify(message,true);}
  finally{previewLoadingKey.current='';setBusy(null);setProgress(null);}
 }
 useEffect(()=>{const handler=(e:KeyboardEvent)=>{const target=e.target as HTMLElement;if(target.matches('input,textarea,select')||target.isContentEditable||modal||busy==='remove-export'||document.querySelector('[role=dialog]'))return;if(e.code==='Space'){e.preventDefault();void preview();}else if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?redo():undo();}else if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='s'){e.preventDefault();void api.saveProject(current.current).then(()=>notify(t("Projekt zapisany."))).catch(error=>notify(error.message,true));}};window.addEventListener('keydown',handler);return()=>window.removeEventListener('keydown',handler);},[playing,busy,modal,notify]);
 async function selectProject(p:Project){if(recordingActive.current||busy==='recording'||busy==='tts'){notify(t("Zakończ pracę z głosem przed zmianą projektu."));return;}if(p.id===current.current.id){setScreen('studio');return;}try{if(ready)await api.saveProject(validateProject(current.current));}catch(e){notify(t("Najpierw popraw zapis bieżącego projektu: {0}", [(e as Error).message]),true);return;}stop();previewKey.current='';setCurrent(library.current.find(x=>x.id===p.id)||p);history.current=[];future.current=[];setSelectedLayer(null);setScreen('studio');}
 function startNew(mode:Mode='classic'){setNewMode(mode);setNewName('');setModal('new');}
 async function create(){if(!newName.trim())return;const p=createProject(newName.trim(),newMode);await selectProject(p);setModal(null);notify(t("Nowa sesja jest gotowa. Zacznij od swojej intencji."));}
 async function importAudio(){if(busy)return;setBusy('import');try{const added=await api.importAudio();setAssets(all=>[...all,...added]);if(added.length){if(screen==='studio'){update(p=>({...p,layers:[...p.layers,...added.slice(0,32-p.layers.length).map((a,i)=>layerFromAsset(a,(['A','B','C'] as Role[])[(p.layers.length+i)%3]))]}));notify(t("Dodano {0} {1} do studia.", [added.length, added.length===1?t('nagranie'):t('nagrania')]));}else notify(t("Dodano do biblioteki: {0}.", [added.length]));}}catch(e){notify((e as Error).message,true);}finally{setBusy(null);}}
 async function importBackground(){if(busy)return;setBusy('import');try{const added=await api.importAudio();setAssets(all=>[...all,...added]);if(added[0]){const a=added[0];update(p=>({...p,background:{...p.background,kind:'file',path:a.path,name:a.name}}));notify(t("Muzyka dodana jako tło. Dopasuj jej poziom w ustawieniach sesji."));}}catch(e){notify((e as Error).message,true);}finally{setBusy(null);}}
 async function importText(){try{const text=await api.importText();if(text===null)return;const lines=parseScript(text);if(!lines.length){notify(t("W pliku nie znaleziono zdań."),true);return;}const replacesTemplate=shouldReplaceTemplateScript(current.current);update(p=>({...p,script:(shouldReplaceTemplateScript(p)?lines:[...p.script,...lines]).slice(0,500)}));notify(replacesTemplate?t("Zaimportowano {0} zdań i zastąpiono przykładowy tekst.", [lines.length]):t("Dodano {0} zdań do skryptu.", [lines.length]));}catch(e){notify((e as Error).message,true);}}
 async function openProject(){try{const data=await api.importProject();if(data){const p=migrateProject(data);selectProject(p);const bootstrap=await api.bootstrap();setAssets(bootstrap.assets);notify(t("Projekt otwarty. Starsze pliki przenoszą tekst i ustawienia; nagrania dodaj z biblioteki."));}}catch(e){notify((e as Error).message,true);}}
 function addLayer(a:Asset,role:Role){if(project.layers.length>=32){notify(t("Sesja może mieć maksymalnie 32 warstwy."),true);return;}update(p=>({...p,layers:[...p.layers,layerFromAsset(a,role)]}));notify(t("Dodano nagranie do warstwy {0}.", [role]));}
 async function generate(voice:string,rate:number,role:Role|'all'){
  if(busy)return;setBusy('tts');const p=current.current;const roles=(role==='all'?['A','B','C']:[role]) as Role[];let count=0;
  try{for(const r of roles){const text=p.script.filter(l=>l.role===r).map(l=>l.text.trim()).filter(Boolean).join('\n\n');if(!text)continue;const a=await api.synthesize({text,voice,rate,name:`${r} · ${roleLabels[r]} · ${p.name}`});setAssets(all=>[...all,a]);update(prev=>prev.id===p.id?{...prev,layers:prev.layers.length<32?[...prev.layers,layerFromAsset(a,r)]:prev.layers}:prev);count++;}notify(t("Wygenerowano {0} {1}. Nagrania są już w studiu.", [count, count===1?t('warstwę'):t('warstwy')]));}catch(e){notify((e as Error).message,true);}finally{setBusy(null);}
 }
 async function recorded(bytes:ArrayBuffer,line?:Line){setBusy('recording');try{const a=await api.saveRecording({bytes,format:'wav',name:line?.text.slice(0,100)||t("Mój głos · {0}", [new Date().toLocaleTimeString(getLocale(),{hour:'2-digit',minute:'2-digit'})])});setAssets(all=>[...all,a]);addLayer(a,line?.role||'A');}catch(e){notify((e as Error).message,true);}finally{setBusy(null);}}
 async function removeExport(result:RenderResult){
   if(busy||recordingActive.current)throw new Error(getLocale()==='pl'?'Zakończ przetwarzanie lub nagrywanie.':'Finish processing or recording first.');
   const p=structuredClone(current.current);stop();setBusy('remove-export');
   try{const response=await api.removeExport({project:p,exportId:result.id});
   const clean=(item:Project)=>item.id===p.id?{...item,exports:item.exports.filter(r=>r.id!==result.id),comparisons:item.comparisons?.filter(c=>c.firstId!==result.id&&c.secondId!==result.id)}:item;
   history.current=history.current.map(clean);future.current=future.current.map(clean);
   if(current.current.id===p.id)setCurrent({...current.current,exports:response.project.exports,comparisons:response.project.comparisons});
   else{library.current=library.current.map(item=>item.id===p.id?response.project:item);setProjects(library.current);}
   }finally{setBusy(null);}
 }
  async function render(format:Format,allVariants=false){if(busy)return;stop();setBusy('render');setProgress({stage:t("Przygotowanie eksportu"),progress:0});const p=structuredClone(current.current);try{for(const variant of allVariants?(p.background.kind!=='none'&&!p.background.muted&&!p.background.solo?(['CLEAR','LOW','MASKED','DEEP'] as const):(['CLEAR','LOW','MASKED'] as const)):[p.variant]){const result=await api.render({project:{...p,variant},format,preview:false});const latest=current.current.id===p.id?current.current:library.current.find(x=>x.id===p.id)||p;const next={...latest,duration:Math.max(latest.duration,result.duration),exports:[...latest.exports,result]};if(current.current.id===p.id)setCurrent(next);else{library.current=library.current.map(x=>x.id===p.id?next:x);setProjects(library.current);}await api.saveProject(next);}notify(allVariants?(getLocale()==='pl'?'Dostępne warianty zostały wyeksportowane.':'Available variants exported.'):t("Nagranie wyeksportowane. Sprawdź raport jakości."));}catch(e){if(!/anul|abort/i.test((e as Error).message))notify((e as Error).message,true);}finally{setBusy(null);setProgress(null);}}
 async function savePortable(){try{if(await api.exportProject(project))notify(t("Zapisano przenośny projekt razem z nagraniami."));}catch(e){notify((e as Error).message,true);}}
 const newModes=[{id:'classic' as Mode,title:'Classic',description:t("Naturalne afirmacje. Spokojne tempo. Przestrzeń na własne słowa."),icon:AudioLines},{id:'forced' as Mode,title:'Forced',description:t("Zdecydowane deklaracje, bezpośrednie intencje i skupiony przekaz."),icon:Sparkles},{id:'spell' as Mode,title:'Spell',description:t("Obrazowy język, rytuał i atmosfera. Sesja z własnym charakterem."),icon:WandSparkles},{id:'forced-spell' as Mode,title:'Forced + Spell',description:t("Zdecydowane deklaracje z obrazowym językiem i rytuałem. Oba style w jednej sesji."),icon:WandSparkles}];
 return <div className="app-shell"><GlassScene/><aside className="sidebar"><Brand/><MaterialSwitch value={theme} onChange={setTheme}/><button className="new-session" onClick={()=>startNew()}><Plus size={17}/>{t("Nowa sesja")}<span>+</span></button><div className="nav-label">{t("TWOJE STUDIO")}</div><nav>{nav.map(n=><button key={n.id} className={screen===n.id?'active':''} onClick={()=>setScreen(n.id)}>{screen===n.id&&<motion.span className="nav-surface" layoutId="nav-surface" transition={{type:'spring',stiffness:430,damping:34}}/>}<n.icon size={18} strokeWidth={1.7}/><span className="nav-text">{t(n.label)}</span>{n.id==='exports'&&project.exports.length>0&&<span className="nav-count">{project.exports.length}</span>}{screen===n.id&&<i/>}</button>)}</nav><div className="recent-projects"><div className="nav-label">{t("OSTATNIE SESJE")}</div>{(projects.length?projects:[project]).slice(0,4).map(p=><button key={p.id} className={p.id===project.id?'current':''} onClick={()=>selectProject(p)}><span className={`project-dot mode-${p.mode}`}/><span>{p.name}</span></button>)}</div><div className="sidebar-bottom"><div className="local-badge"><span className="local-icon"><HardDrive size={16}/></span><div>{t("Twoje dźwięki zostają z Tobą.")}<small>{t("Projekty przechowywane lokalnie")}</small></div></div><button className="settings-button" onClick={()=>setModal('settings')}><Settings size={17}/>{t("Ustawienia")}<span>v2.2</span></button></div></aside>
 <div className="app-body"><header className="topbar"><div className="breadcrumbs"><span>Auralith Studio</span><span>/</span><input aria-label={t("Nazwa projektu")} value={project.name} maxLength={200} onChange={e=>update(p=>({...p,name:e.target.value}))}/></div><div className="top-actions"><span className={`save-state ${saveStatus}`} title={saveStatus==='error'?t("Sprawdź nazwę projektu i ustawienia"):t("Automatyczny zapis")}>{saveStatus==='saving'?<LoaderCircle size={13} className="spin"/>:saveStatus==='error'?<AlertCircle size={13}/>:<Check size={13}/>}<span>{saveStatus==='saving'?t("Zapisywanie"):saveStatus==='error'?t("Nie zapisano"):t("Zapisano")}</span></span><button className="icon-button" title={t("Cofnij (Ctrl+Z)")} aria-label={t("Cofnij")} onClick={undo}><Undo2 size={16}/></button><button className="button small export-top" onClick={()=>setScreen('exports')}><Download size={15}/>{t("Eksportuj")}</button><div className="window-controls"><button aria-label={t("Minimalizuj")} onClick={()=>api.windowControl('minimize')}><Minus size={14}/></button><button aria-label={t("Maksymalizuj")} onClick={()=>api.windowControl('maximize')}><Maximize2 size={12}/></button><button aria-label={t("Zamknij aplikację")} className="window-close" onClick={()=>api.windowControl('close')}><X size={15}/></button></div></div></header>
 <motion.div className="view-container" key={screen} initial={{opacity:0,y:reduced?0:12,scale:reduced?1:.995}} animate={{opacity:1,y:0,scale:1}} transition={{type:"spring",stiffness:460,damping:36,mass:.7}}>
 {screen==='studio'&&<Studio project={project} update={update} addAudio={()=>void importAudio()} importBackground={()=>void importBackground()} goVoices={()=>setScreen('voices')} position={position} selectedId={selectedLayer} selectLayer={setSelectedLayer} busy={!!busy}/>}
 {screen==='script'&&<ScriptLab project={project} update={update} importText={()=>void importText()} goVoices={()=>setScreen('voices')}/>}
 {screen==='voices'&&<Voices project={project} assets={assets} busy={busy} generate={generate} importAudio={()=>void importAudio()} addLayer={addLayer} recorded={recorded} removeAsset={async id=>{setBusy('remove');try{await api.removeAsset(id);setAssets(all=>all.filter(a=>a.id!==id));notify(getLocale()==='pl'?'Usunięto z biblioteki. Warstwy w projektach zachowują audio.':'Removed from library. Project tracks keep their audio.');}catch(e){notify((e as Error).message,true);}finally{setBusy(null);}}} play={url=>void playUrl(url)} goStudio={()=>setScreen('studio')} useBackground={a=>{update(p=>({...p,background:{...p.background,kind:'file',path:a.path,name:a.name}}));notify(t("Nagranie ustawione jako tło sesji."));}} notify={notify} onRecordingChange={active=>{recordingActive.current=active;}}/>}
 {screen==='exports'&&<Exports project={project} removeExport={removeExport} update={update} render={render} busy={busy} play={url=>void playUrl(url)} reveal={path=>void api.reveal(path).catch(e=>notify(e.message,true))} saveFile={path=>void api.exportFile(path).then(ok=>{if(ok)notify(t("Plik zapisany."));}).catch(e=>notify(e.message,true))}/>}
 {screen==='projects'&&<div className="content-page projects-page"><div className="page-heading"><div><span className="eyebrow">{t("MAŁE INTENCJE. WŁASNY RYTM.")}</span><h1>{t("Przestrzeń na ")}<em>{t("Twoje sesje.")}</em></h1><p>{t("Wracaj do tego, co ważne. Albo zacznij zupełnie nowy rozdział.")}</p></div><button className="button ghost" onClick={()=>void openProject()}><FolderOpen size={16}/>{t("Otwórz projekt")}</button></div><div className="preset-heading"><h2>{t("Od czego zaczynamy?")}</h2><span>{t("WYBIERZ PUNKT WYJŚCIA")}</span></div><div className="preset-grid">{newModes.map((m,i)=><button key={m.id} className={`preset-card preset-${m.id}`} onClick={()=>startNew(m.id)}><div className="preset-art"><div className="preset-lines">{Array.from({length:9},(_,n)=><i key={n}/>)}</div><m.icon size={26}/></div><div className="preset-copy"><h2>{m.title}</h2><p>{m.description}</p><ArrowUpRight size={19}/></div></button>)}</div><div className="subheading sessions-heading"><div><span className="eyebrow">{t("ZAPISANE NA TYM KOMPUTERZE")}</span><h2>{t("Twoje projekty")}</h2></div><label className="search-box"><Search size={16}/><input placeholder={t("Znajdź sesję…")} aria-label={t("Znajdź sesję")} value={search} onChange={e=>setSearch(e.target.value)}/></label></div><div className="project-list">{(projects.length?projects:[project]).filter(p=>p.name.toLowerCase().includes(search.toLowerCase())).map(p=><button key={p.id} className="project-row" onClick={()=>selectProject(p)}><span className={`project-art mode-${p.mode}`}><AudioLines size={24}/></span><div><strong>{p.name}</strong><small>{p.script.length} {t(" zdań · ")}{p.layers.length} {t(" warstw · ")}{clock(p.duration)}</small></div><span className={`mode-pill mode-${p.mode}`}>{modeLabels[p.mode]}</span><time>{formatDate(p.updatedAt)}</time><ArrowUpRight size={17}/></button>)}</div></div>}
 </motion.div>
 <footer className="transport"><div className="transport-info"><span className={`transport-art ${playing?'is-playing':''}`}><AudioLines size={21}/></span><div><strong>{project.name}</strong><span>{busy==='preview'?t("Przygotowanie odsłuchu…"):tMessage(playbackName)}</span></div></div><div className="transport-center"><div className="transport-buttons"><button className="icon-button" aria-label={t("Wróć do początku")} onClick={stop}><SkipBack size={17}/></button><motion.button whileTap={{scale:.86}} whileHover={{scale:1.055}} transition={{type:'spring',stiffness:420,damping:25}} className="transport-play" aria-label={playing?t("Wstrzymaj"):t("Odsłuchaj sesję")} disabled={!!busy||!ready} onClick={()=>void preview()}>{busy==='preview'?<LoaderCircle size={21} className="spin"/>:playing?<Pause size={19} fill="currentColor"/>:<Play size={20} fill="currentColor"/>}</motion.button><button className="icon-button" aria-label={t("Zatrzymaj")} onClick={stop}><Square size={13}/></button></div><div className="transport-progress"><span>{clock(position)}</span><input type="range" min={0} max={playDuration||project.duration} value={position} step={.05} disabled={!audio.current?.src} aria-label={t("Pozycja odsłuchu")} onChange={e=>{if(audio.current)audio.current.currentTime=Number(e.target.value);setPosition(Number(e.target.value));}}/><span>{clock(playDuration||project.duration)}</span></div></div><div className="transport-volume"><Headphones size={15}/><span>{t("ODSŁUCH")}</span><Volume2 size={16}/><input aria-label={t("Głośność odsłuchu")} type="range" min={0} max={1} step={.01} value={volume} onChange={e=>setVolume(Number(e.target.value))}/><span>{Math.round(volume*100)}%</span></div></footer>
 </div><audio ref={audio} onPlay={()=>setPlaying(true)} onPause={()=>setPlaying(false)} onEnded={()=>setPlaying(false)} onTimeUpdate={()=>setPosition(audio.current?.currentTime||0)} onLoadedMetadata={()=>setPlayDuration(Number.isFinite(audio.current?.duration)?audio.current!.duration:0)} onError={()=>{if(audio.current?.getAttribute('src'))notify(t("Nie można odtworzyć nagrania."),true);}}/>
 {progress&&<div className="render-progress" role="status"><div><LoaderCircle size={17} className="spin"/><strong>{tMessage(progress.stage)}</strong><span>{Math.round(progress.progress*100)}%</span><button className="text-button" onClick={()=>void api.cancelRender()}>{t("Anuluj")}</button></div><div className="progress-track"><i style={{transform:`scaleX(${Math.max(0,Math.min(1,progress.progress))})`}}/></div></div>}
 {toast&&<div className={`toast ${toast.error?'error':''}`} role={toast.error?'alert':'status'}>{toast.error?<AlertCircle size={18}/>:<Check size={18}/>}<span>{tMessage(toast.message)}</span><button aria-label={t("Zamknij powiadomienie")} onClick={()=>setToast(null)}><X size={15}/></button></div>}
 <AnimatePresence>{modal==='new'&&<Modal key="new" title={t("Nowa sesja")} onClose={closeModal} wide><p className="modal-intro">{t("Wybierz charakter sesji. Każdy szczegół możesz później dostosować.")}</p><label className="field">{t("Nazwa sesji")}<input placeholder={t("Na przykład: Spokojna pewność")} maxLength={200} value={newName} onChange={e=>setNewName(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')create();}} autoFocus/></label><div className="mode-options">{newModes.map(m=><button key={m.id} className={`${newMode===m.id?'selected':''} mode-${m.id}`} onClick={()=>setNewMode(m.id)}><m.icon size={23}/><strong>{m.title}</strong><span>{m.description}</span></button>)}</div><p className="modal-note">{t("Forced i Spell to kreatywne szablony tekstu. Głośność i sposób miksowania ustawisz niezależnie w studiu.")}</p><footer className="modal-actions"><button className="button ghost" onClick={closeModal}>{t("Anuluj")}</button><button className="button primary" disabled={!newName.trim()} onClick={create}>{t("Utwórz sesję ")}<ArrowRight size={16}/></button></footer></Modal>}
 {modal==='settings'&&<Modal key="settings" title={t("Twoje studio, po Twojemu")} onClose={closeModal}><div className="settings-section"><span className="eyebrow">{t('Język')}</span><label className="field">{t('Język interfejsu')}<select aria-label={t('Język interfejsu')} value={locale} onChange={e=>setLocale(e.target.value as 'en'|'pl')}><option value="en">English</option><option value="pl">Polski</option></select></label><p>{t('Zmiana języka nie zmienia tekstu ani nagrań projektu.')}</p></div><div className="settings-section"><span className="eyebrow">{t("WYGLĄD")}</span><h3>{t("Materiał interfejsu")}</h3><MaterialSwitch value={theme} onChange={setTheme}/><p>{t("Liquid Glass: matowe szkło i światło. Focus: pełne, nieprzezroczyste powierzchnie.")}</p></div><MotionSettings/><div className="settings-section"><span className="eyebrow">{t("PROJEKT I BIBLIOTEKA")}</span><h3>{t("Zabierz sesję ze sobą")}</h3><p>{t("Przenośny projekt zawiera tekst, ustawienia i użyte nagrania.")}</p><button className="button" onClick={()=>{void selectProject(duplicateProject(current.current));closeModal();}}><Plus size={16}/>{t("Duplikuj sesję jako własny szablon")}</button><button className="button" onClick={()=>void savePortable()}><Download size={16}/>{t("Zapisz projekt z nagraniami")}</button><p className="data-path"><HardDrive size={14}/>{tMessage(appInfo.dataPath)}</p></div><div className="settings-section"><span className="eyebrow">{t("SKRÓTY KLAWIATUROWE")}</span><div className="shortcut-list"><span>{t("Odsłuch / pauza")}</span><kbd>{t("Spacja")}</kbd><span>{t("Zapisz")}</span><kbd>Ctrl S</kbd><span>{t("Cofnij / przywróć")}</span><kbd>Ctrl ⇧ Z</kbd></div></div><Updates install={async()=>{if(busy||recordingActive.current)throw new Error('Finish recording or processing first.');await api.saveProject(current.current);if(!api.installUpdate)throw new Error('Updater unavailable');await api.installUpdate();}}/><Support open={url=>api.openSupport?api.openSupport(url):unavailable()}/><div className="settings-footer"><Brand/><span>{tMessage(appInfo.version)}<br/>{t("Lokalne studio audio")}</span></div></Modal>}</AnimatePresence>
 </div>;
}

